"""add task isCompleted column

Revision ID: 49223dc127da
Revises: 7e1145661bf8
Create Date: 2023-10-09 16:39:18.292316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49223dc127da'
down_revision = '7e1145661bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isComleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('isComleted')

    # ### end Alembic commands ###
