"""create priority foreign key

Revision ID: 7e1145661bf8
Revises: f419632cbba6
Create Date: 2023-10-09 14:32:32.137419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1145661bf8'
down_revision = 'f419632cbba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_priority', 'priority', ['priority_id'], ['priority_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_priority', type_='foreignkey')
        batch_op.drop_column('priority_id')

    # ### end Alembic commands ###
